services:
  php:
    image: indominus/frankenphp-php
    build:
      context: .
      target: prod
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MAILER_DSN: smtp://${MAILER_USER}:${MAILER_PASS}@mailpit:1025
      DATABASE_URL: mysql://${DB_USER}:${DB_PASS}@db:3306/${DB_NAME}?serverVersion=11.5.2-MariaDB&charset=utf8mb4
      MESSENGER_TRANSPORT_DSN: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/%2f
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
      - ./supervisor-consumers.conf:/etc/supervisor/conf.d/supervisor-consumers.conf:ro
    ports:
      - target: 80
        published: "${HTTP_PORT:-80}"
        protocol: tcp
      - target: 443
        published: "${HTTPS_PORT:-443}"
        protocol: tcp
      - target: 443
        published: "${HTTP3_PORT:-443}"
        protocol: udp

volumes:
  caddy_data:
  caddy_config:
